install.packages("PerformanceAnalytics")
install.packages("RColorBrewer")
install.packages("caret")
install.packages("ggiraph")
install.packages("ggiraphExtra")
library(ggiraph)
library(ggiraphExtra)
library(caret)
library(PerformanceAnalytics)
library(RColorBrewer)
library(corrplot)
library(readxl)
library(tidyverse)
library(broom)
library(rsample)
Fish <- read_excel("~/Downloads/Fish.xlsx", 
                      skip = 1)
head(Fish)
Fish <- Fish %>% select(-Length2)
summary(Fish)
##EDA##
ggplot(Fish, aes(x = Weight, y = Length1, color = Species)) + geom_point() + geom_jitter(alpha = .5) 
ggplot(Fish, aes(x = Weight, y = Length3, color = Species)) + geom_point() + geom_jitter(alpha = .5)
ggplot(Fish, aes(x = Weight, y = Height, color = Species)) + geom_point() + geom_jitter(alpha = .5)
ggplot(Fish, aes(x = Weight, y = Width, color = Species)) + geom_point() + geom_jitter(alpha = .5)
ggplot(Fish, aes(x = Length1, y = Length3, color = Species)) + geom_point() + geom_jitter(alpha = .5)
ggplot(Fish, aes(x = Height, y = Width, color = Species)) + geom_point() + geom_jitter(alpha = .5)
Fish %>% count(Species) %>% mutate(Species = fct_reorder(Species, n, .desc = TRUE)) %>%
  ggplot(aes(x = Species, y = n)) + geom_bar(stat = 'identity')
ggplot(Fish, aes(x = Height, y = Weight, color = Species)) + geom_point()
##correlation graph##
Fish1 <- Fish[, 2:6]
chart.Correlation(Fish1, histogram = TRUE, pch = 19)
##Linear Regression##
set.seed(42)
Fish_split <- initial_split(Fish, prop = .75)
training_data <- training(Fish_split)
testing_data <- testing(Fish_split)
dim(training_data)
dim(testing_data)
model <- lm(Weight ~ factor(Species) + Length1 + Length3 + Height + Width, data = training_data)
Fish_predict <- predict(model, newdata = testing_data)
error <- Fish_predict - testing_data[["Weight"]]
sqrt(mean(error^2))
summary(model)
##cross validation##
model2 <- train(Weight ~ factor(Species) + Length1 + Length3 + Height + Width, data = Fish, method = "lm", trControl = trainControl(method = "cv", number = 10, verboseIter = TRUE))
print(model2)
Fish_predict_final <- predict(model2, Fish)
Fish_predict_dataframe <- data.frame(wgt_predicted = predict(model2, Fish))
